# Generated by Django 4.1.3 on 2022-12-07 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, max_length=30, verbose_name='Apellido')),
                ('fecha_nacimiento', models.DateField()),
                ('dni', models.PositiveIntegerField()),
                ('sueldo', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
            },
        ),
        migrations.CreateModel(
            name='Posición',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posición', models.CharField(choices=[('0', 'Arquero'), ('1', 'Defensor'), ('2', 'Medio campo'), ('3', 'Delantero')], max_length=1, verbose_name='Posición')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jugador.jugador')),
            ],
            options={
                'verbose_name': 'Posición',
                'verbose_name_plural': 'Posiciónes',
            },
        ),
        migrations.CreateModel(
            name='País',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=30, null=True, verbose_name='Club')),
                ('país', models.CharField(max_length=30, null=True, verbose_name='País')),
                ('jugador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jugador.jugador')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
            },
        ),
    ]
