# Generated by Django 4.1.3 on 2022-12-06 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jugador', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jugador',
            old_name='fecha_nacimento',
            new_name='fecha_nacimiento',
        ),
    ]
