# Generated by Django 4.1.3 on 2022-12-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='país',
            name='club',
            field=models.CharField(max_length=50, null=True, verbose_name='Club'),
        ),
    ]
