# Generated by Django 4.1.3 on 2022-12-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugador', '0003_alter_posición_posición'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='sueldo_anual',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
